config/routes.rb
Rails.application.routes.draw do
 

  resources :accounts

end

app/models/account.rb
class Account < ActiveRecord::Base
	has_many :account_entries
end

app/models/account_entry.rb
class AccountEntry < ActiveRecord::Base
		belongs_to :account

app/models/customer.rb
class Customer < Account
	has_many :time_entries

end

@customer.time_entries #only TimeEntries
@customer.account_entries #a mix of TimeEntries and AccountEntries

app/models/employee.rb
class Employee < Account
	has_many :time_entries
	has_and_belongs_to_many :projects, :join_table => "employees_projects"


	def total_hours
		time_entries.sum(:time)
	end

	def log_time(amount, customer)
		TimeEntry.create(time: amount, employee: self, acount: customer)
	end
end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :customer
	has_and_belongs_to_many :employees, :join_table => "employees_projects"
end

app/models/time_entry.rb
class TimeEntry < AccountEntry
	belongs_to :employee
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

	def index 
		@accounts = Account.all
	end

	def show
		@account = @accounts.find(params[:id])
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/index.html.erb
<table>
	<% @accounts.each do |account|%>
	<tr>
		<td>
			<%= link_to account.name, account_path(account) %>
		</td>
		<td>
			<%= account.type.to_s %>
		</td>
	</tr> 
	<% end %>

</table>

app/views/accounts/show.html.erb
<h1><%= @account.name %></h1>

Total Hours: <%= @account.account_entries.sum(:time) %>
Total Cost: $<%= (@account.account_entries.map &:cost).sum %>

<h4>Account Entries</h4>

<table>
	<% @account.account_entries.each do |entry| %>
	<tr>
		<td><%= entry.created_at %></td>
		<td><%= entry.employee.name %></td>
		<td><%= entry.time %> hours</td>
	</tr>
	<% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Biller</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>